client_config_backend: settings
client_config:
  cliend_id: 1069578599391-0r5e3t7qhggoac8ntea573396257ps6f.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

ouauth_scope:
   - https://www.googleapis.com/auth/drive