client_config_backend: settings
client_config:
  cliend_id: 629664585428-fou8udvsnkisd3nu37up72j2cl9p889d.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

ouauth_scope:
   - https://www.googleapis.com/auth/drive